routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SignController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Session()->reflash();
    return redirect('/search');
});
Route::get('/home', function () {
    Session()->reflash();
    return redirect('/search');
});

Auth::routes(['register' => false]);

Route::resource('signs', 'SignController');

Route::get('/search', function () {
    return view('search');
})->name('search');

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {

        // admin sign routes
        Route::get('/signs', [SignController::class, 'index'])->middleware('permission:create_signs|edit_signs|delete_signs')->name('signs.index');
        Route::get('/signs/create', [SignController::class, 'create'])->middleware('permission:create_signs')->name('signs.create');
        Route::post('/signs', [SignController::class, 'store'])->middleware('permission:create_signs')->name('signs.store');
        Route::get('/signs/{sign}/edit', [SignController::class, 'edit'])->middleware('permission:edit_signs')->name('signs.edit');
        Route::put('/signs/{sign}', [SignController::class, 'update'])->middleware('permission:edit_signs')->name('signs.update');
        Route::delete('/signs/{sign}', [SignController::class, 'destroy'])->middleware('permission:delete_signs')->name('signs.destroy');

        // admin user routes
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:create_users|edit_users|delete_users')->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->middleware('permission:create_users')->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:create_users')->name('users.store');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->middleware('permission:edit_users')->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:edit_users')->name('users.update');
        Route::delete('/users/{id}/toggleStatus', [UserController::class, 'toggleStatus'])->middleware('permission:delete_users')->name('users.toggleStatus');

        // admin role routes
        Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:create_roles|edit_roles|delete_roles')->name('roles.index');
        Route::get('/roles/create', [RoleController::class, 'create'])->middleware('permission:create_roles')->name('roles.create');
        Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:create_roles')->name('roles.store');
        Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->middleware('permission:edit_roles')->name('roles.edit');
        Route::put('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:edit_roles')->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:delete_roles')->name('roles.destroy');
    });

Route::get('/changePassword', [UserController::class, 'changePasswordForm'])->name('changePasswordForm');
Route::post('/changePassword', [UserController::class, 'changePassword'])->name('changePassword');

Route::get('/{page}', 'PageController')
    ->name('page')
    ->where('page', 'about|services|contact');

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $roles = Role::get();
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::get()->groupBy('group');
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // Validate Request Data
        $validatedData = $request->validate([
            'name' => 'required|unique:roles',
            'permissions.*' => Rule::in(Permission::pluck('name')->toArray())
        ]);

        $role = Role::create(['name' => $validatedData['name']]);

        if (!isset($validatedData['permissions'])) $validatedData['permissions'] = null;
        $role->syncPermissions($validatedData['permissions']);
        $role->save();

        flashMessage('Role created.', 'success');

        return redirect()->route('admin.roles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role) {
        // Super Admins should not be editable
        if ($role->name == 'Super-Admin' || $role->name == 'User') {
            flashMessage('Cannot update this role!', 'warning');
            return redirect()->route('admin.roles.index');
        }

        $permissions = Permission::get()->groupBy('group');
        return view('admin.roles.create', compact('permissions', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role) {
        // Super Admins should not be editable
        if ($role->name == 'Super-Admin' || $role->name == 'User') {
            flashMessage('Cannot update this role!', 'warning');
            return redirect()->route('admin.roles.index');
        }

        // Validate Request Data
        $validatedData = $request->validate([
            'name' => 'required',
            'permissions.*' => Rule::in(Permission::pluck('name')->toArray())
        ]);

        if (!isset($validatedData['permissions'])) $validatedData['permissions'] = null;
        $role->syncPermissions($validatedData['permissions']);
        $role->save();

        flashMessage('Role updated.', 'success');

        return redirect()->route('admin.roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role) {
        // Super Admins should not be editable
        if ($role->name == 'Super-Admin' || $role->name == 'User') {
            flashMessage('Cannot delete this role!', 'warning');
            return redirect()->route('admin.roles.index');
        }

        // Cannot delete role with users
        if ($role->users()->count()) {
            flashMessage('Cannot delete role with users!', 'warning');
            return redirect()->route('admin.roles.index');
        }

        $role->delete();

        flashMessage('Role deleted.', 'success');

        return redirect()->route('admin.roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">{{ isset($role) ? 'Edit Role' : 'Add Role' }}</h4>
                    @if (isset($role))

                    <a class="btn btn-danger text-white" href="#" onclick="handleDelete(event)">Delete
                        Role</a>
                    <form id="deleteForm" action="{{ route('admin.roles.destroy', $role->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                    </form>
                    @endif
                </div>

                <div class="card-body">

                    <form action="{{ isset($role) ? route('admin.roles.update', $role->id) : route('admin.roles.store') }}"
                          method="POST" enctype="multipart/form-data">
                        @csrf

                        {{-- Change method if update --}}
                        @if (isset($role))
                        @method('PUT')
                        @endif

                        <div class="card-block">

                            <div class="form-group">
                                <label>Name</label><br>
                                <input value="{{ old('name', isset($role) ? $role->name : '') }}" class="form-control"
                                       type="text" name="name" />
                            </div>

                            <fieldset class="form-group border px-4 pb-4">
                                <legend class="w-auto px-2">Permissions</legend>
                                <div class="d-flex flex-wrap gap-20 justify-content-between">
                                    @foreach ($permissions as $group)
                                    <div class="d-flex flex-column">
                                        <label>
                                            <b>{{ $group[0]->group }}</b>
                                        </label>
                                        <div>
                                            @foreach ($group as $permission)
                                            <label class="ml-3">
                                                <input type="checkbox" name="permissions[]" id=""
                                                       value="{{ $permission->name }}" {{ isset($role) ?
                                                       ($role->hasPermissionTo($permission->name) ? 'checked' : '') : ''
                                                }}/>
                                                {{ $permission->name }}
                                            </label><br>
                                            @endforeach
                                        </div>
                                    </div>
                                    @endforeach
                                </div>
                            </fieldset>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">{{ isset($role) ? 'Submit Changes' : 'Add'
                                    }}</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_css')
<link rel="stylesheet" href="/css/select2.min.css">
@endsection
@section('additional_js')
<script>
    const handleDelete = (e) => {
    e.preventDefault();
    const del = confirm('DELETE this role?');
    if(del) {
        const form = document.querySelector('#deleteForm');
        form.submit();
    }
}
</script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">Roles</h4>

                    @can('create_roles')
                    <a class="btn btn-success text-white" href="{{ route('admin.roles.create') }}">+ Add role</a>
                    @endcan
                </div>

                <div class="card-body">
                    <table class="table m-0 border">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>User count</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($roles as $role)
                            @if ($role->name != 'Super-Admin')
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->users()->count() }}</td>
                                <td>
                                    @can('edit_roles')
                                    @if ($role->name != "User")
                                    <a href="{{ route('admin.roles.edit', $role->id) }}">Edit</a>
                                    @endif
                                    @endcan
                                </td>
                            </tr>
                            @endif
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_css')
@endsection
@section('additional_js')
@endsection