routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SignController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Session()->reflash();
    return redirect('/search');
});
Route::get('/home', function () {
    Session()->reflash();
    return redirect('/search');
});

Auth::routes(['register' => false]);

Route::resource('signs', 'SignController');

Route::get('/search', function () {
    return view('search');
})->name('search');

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {

        // admin sign routes
        Route::get('/signs', [SignController::class, 'index'])->middleware('permission:create_signs|edit_signs|delete_signs')->name('signs.index');
        Route::get('/signs/create', [SignController::class, 'create'])->middleware('permission:create_signs')->name('signs.create');
        Route::post('/signs', [SignController::class, 'store'])->middleware('permission:create_signs')->name('signs.store');
        Route::get('/signs/{sign}/edit', [SignController::class, 'edit'])->middleware('permission:edit_signs')->name('signs.edit');
        Route::put('/signs/{sign}', [SignController::class, 'update'])->middleware('permission:edit_signs')->name('signs.update');
        Route::delete('/signs/{sign}', [SignController::class, 'destroy'])->middleware('permission:delete_signs')->name('signs.destroy');

        // admin user routes
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:create_users|edit_users|delete_users')->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->middleware('permission:create_users')->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:create_users')->name('users.store');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->middleware('permission:edit_users')->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:edit_users')->name('users.update');
        Route::delete('/users/{id}/toggleStatus', [UserController::class, 'toggleStatus'])->middleware('permission:delete_users')->name('users.toggleStatus');

        // admin role routes
        Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:create_roles|edit_roles|delete_roles')->name('roles.index');
        Route::get('/roles/create', [RoleController::class, 'create'])->middleware('permission:create_roles')->name('roles.create');
        Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:create_roles')->name('roles.store');
        Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->middleware('permission:edit_roles')->name('roles.edit');
        Route::put('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:edit_roles')->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:delete_roles')->name('roles.destroy');
    });

Route::get('/changePassword', [UserController::class, 'changePasswordForm'])->name('changePasswordForm');
Route::post('/changePassword', [UserController::class, 'changePassword'])->name('changePassword');

Route::get('/{page}', 'PageController')
    ->name('page')
    ->where('page', 'about|services|contact');

resources/views/partials/flash-messages.blade.php
@if (session('status'))
<div class="status container pt-4">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>

        </div>
    </div>
</div>
@endif

@if ($messages = Session::get('messages'))
<div class="messages container pt-4">
    <div class="row justify-content-center">
        <div class="col-md-12">

            @foreach ($messages as $message => $type)
            <div class="alert alert-{{ $type ? $type : 'info' }} alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
            @endforeach

        </div>
    </div>
</div>
@endif

@if ($errors->any())
<div class="errors container pt-4">
    <div class="row justify-content-center">
        <div class="col-md-12">

            @foreach ($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $error }}</strong>
            </div>
            @endforeach

        </div>
    </div>
</div>
@endif

resources/views/partials/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('about') ? 'active' : '' }}"
                       href="{{ route('page', 'about') }}">{{
                        __('About') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('services') ? 'active' : '' }}"
                       href="{{ route('page', 'services') }}">{{
                        __('Services') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('contact') ? 'active' : '' }}"
                       href="{{ route('page', 'contact') }}">{{
                        __('Contact') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('search') ? 'active' : '' }}" href="{{ route('search') }}">{{
                        __('Search Sign')
                        }}</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest

                {{-- Login Link --}}
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                {{-- Login Link --}}

                {{-- Registration Link --}}
                {{-- @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
                @endif --}}
                {{-- Registration Link --}}

                @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    {{-- DEBUG --}}
                    {{-- @foreach (Auth::user()->roles as $role)
                    {{ $role->name }} ->
                    @foreach ($role->permissions as $perm)
                    {{ $perm->name }} |
                    @endforeach
                    <br>
                    @endforeach
                    {{ Auth::user()->hasRole('Super-Admin') }} --}}

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                        @canany(['create_signs', 'edit_signs', 'delete_signs'])
                        <a class="dropdown-item" href="{{ route('admin.signs.index') }}">
                            {{ __('Manage Signs') }}
                        </a>
                        @endcanany

                        @canany(['create_users', 'edit_users', 'delete_users'])
                        <a class="dropdown-item" href="{{ route('admin.users.index') }}">
                            {{ __('Manage Users') }}
                        </a>
                        @endcanany

                        @canany(['create_roles', 'edit_roles', 'delete_roles'])
                        <a class="dropdown-item" href="{{ route('admin.roles.index') }}">
                            {{ __('Manage Roles') }}
                        </a>
                        @endcanany

                        <a class="dropdown-item" href="{{ route('changePasswordForm') }}">
                            {{ __('Change Password') }}
                        </a>

                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>