routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SignController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Session()->reflash();
    return redirect('/search');
});
Route::get('/home', function () {
    Session()->reflash();
    return redirect('/search');
});

Auth::routes(['register' => false]);

Route::resource('signs', 'SignController');

Route::get('/search', function () {
    return view('search');
})->name('search');

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {

        // admin sign routes
        Route::get('/signs', [SignController::class, 'index'])->middleware('permission:create_signs|edit_signs|delete_signs')->name('signs.index');
        Route::get('/signs/create', [SignController::class, 'create'])->middleware('permission:create_signs')->name('signs.create');
        Route::post('/signs', [SignController::class, 'store'])->middleware('permission:create_signs')->name('signs.store');
        Route::get('/signs/{sign}/edit', [SignController::class, 'edit'])->middleware('permission:edit_signs')->name('signs.edit');
        Route::put('/signs/{sign}', [SignController::class, 'update'])->middleware('permission:edit_signs')->name('signs.update');
        Route::delete('/signs/{sign}', [SignController::class, 'destroy'])->middleware('permission:delete_signs')->name('signs.destroy');

        // admin user routes
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:create_users|edit_users|delete_users')->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->middleware('permission:create_users')->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:create_users')->name('users.store');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->middleware('permission:edit_users')->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:edit_users')->name('users.update');
        Route::delete('/users/{id}/toggleStatus', [UserController::class, 'toggleStatus'])->middleware('permission:delete_users')->name('users.toggleStatus');

        // admin role routes
        Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:create_roles|edit_roles|delete_roles')->name('roles.index');
        Route::get('/roles/create', [RoleController::class, 'create'])->middleware('permission:create_roles')->name('roles.create');
        Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:create_roles')->name('roles.store');
        Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->middleware('permission:edit_roles')->name('roles.edit');
        Route::put('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:edit_roles')->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:delete_roles')->name('roles.destroy');
    });

Route::get('/changePassword', [UserController::class, 'changePasswordForm'])->name('changePasswordForm');
Route::post('/changePassword', [UserController::class, 'changePassword'])->name('changePassword');

Route::get('/{page}', 'PageController')
    ->name('page')
    ->where('page', 'about|services|contact');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable {
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $users = User::get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $roles = Role::where('name', '!=', 'Super-Admin')->get();
        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validatedData = $request->validate([
            // validate to see if roles are of the expected values
            'role' => [Rule::in(Role::pluck('name')->toArray()), 'not_in:Super-Admin', 'required'],

            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);

        // create user with form data
        $user = User::create([
            'name' => $validatedData['name'],
            'email' => $validatedData['email'],
            'password' => Hash::make($validatedData['password']),
        ]);

        // delete all previous roles and set the selected roles
        $user->syncRoles($validatedData['role']);
        $user->save();

        flashMessage('User created', 'success');

        return redirect()->route('admin.users.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        // Super Admins should not be editable
        if ($user->hasRole('Super-Admin')) {
            flashMessage('Cannot update this user!', 'warning');
            return redirect('admin/users');
        }

        $roles = Role::where('name', '!=', 'Super-Admin')->get();

        return view('admin.users.create', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user) {
        // deny if trying to edit a super admin
        if ($user->hasRole('Super-Admin')) {
            flashMessage('Cannot update this user!', 'warning');
            return redirect()->route('admin.users.index');
        }

        // validate to see if roles are of the expected values
        $validatedData = $request->validate([
            'role' => [Rule::in(Role::pluck('name')->toArray()), 'not_in:Super-Admin', 'required']
        ]);

        // delete all previous roles and set the selected roles
        $user->syncRoles($validatedData['role']);
        $user->save();

        flashMessage('Updated user roles successfully', 'success');

        return redirect()->route('admin.users.index');
    }

    public function toggleStatus(Request $request, $id) {
        // check if previous url parameter id and current id matches
        $previousId = $this->prev_segments(url()->previous())[2];
        if ($previousId != $id) {

            flashMessage('Could not complete action. There was an error!', 'danger');
            return redirect()->back();
        }

        $user = User::findOrFail($id);
        $user->status = !$user->status;
        $user->save();

        if ($user->status) flashMessage('User activated', 'info');
        else flashMessage('User disabled', 'danger');

        return redirect()->back();
    }

    public function changePasswordForm() {
        return view('admin.users.changePassword');
    }

    public function changePassword(Request $request) {

        $request->validate([
            'current_password' => ['required', function ($attribute, $value, $fail) {
                if (!Hash::check($value, Auth()->user()->getAuthPassword())) {
                    $fail('Incorrect Current Password');
                };
            }],
            'new_password' => 'required|confirmed'
        ]);

        $user = User::find(Auth()->user()->id);
        $user->password = Hash::make($request->new_password);
        $user->save();

        flashMessage('Password changed!', 'success');

        return redirect()->back();
    }

    /**
     * Get all of the segments for the previous uri.
     *
     * @return array
     */
    public function prev_segments($uri) {
        $segments = explode('/', str_replace('' . url('') . '', '', $uri));

        return array_values(array_filter($segments, function ($value) {
            return $value !== '';
        }));
    }
}

resources/views/admin/users/changePassword.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">Change Password</h4>
                </div>

                <div class="card-body">
                    <form action="{{ route('changePassword') }}" method="POST">
                        @csrf

                        <div class="card-block">

                            <div class="form-group">
                                <label>Current Password</label><br>
                                <input value="" name="current_password" type="password" class="form-control peakable"
                                       required />
                            </div>
                            <div class="form-group">
                                <label>New Password</label><br>
                                <input name="new_password" type="password" class="form-control peakable" required />
                            </div>

                            <div class="form-group">
                                <label>Confirm New Password</label><br>
                                <input name="new_password_confirmation" type="password" class="form-control peakable"
                                       required />
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_js')
<script type="module">
    import { makePeakable } from '/js/peakable.js'
    makePeakable('.peakable')
</script>
@endsection

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">{{ isset($user) ? 'Edit User Roles' : 'Add User' }}</h4>

                    @can('delete_users')
                    @if (isset($user))
                    <a class="btn btn-{{ $user->status ? 'danger' : 'info' }} text-white" href="#"
                       onclick="handleToggleStatus(event)">{{ $user->status ? 'Disable User' : 'Re-Activate User' }}</a>
                    <form id="toggleStatusForm" action="{{ route('admin.users.toggleStatus', $user->id) }}"
                          method="POST">
                        @csrf
                        @method('PUT')
                    </form>
                    @endif
                    @endcan


                </div>

                <div class="card-body">

                    <form action="{{ isset($user) ? route('admin.users.update', $user->id) : route('admin.users.store') }}"
                          method="POST" enctype="multipart/form-data">
                        @csrf

                        {{-- Change method if update --}}
                        @if (isset($user))
                        @method('PUT')
                        @endif

                        <div class="card-block">

                            <div class="form-group">
                                <label>Name</label><br>
                                <input value="{{ old('name', isset($user) ? $user->name : '') }}" name="name"
                                       type="text" class="form-control" {{ isset($user) ? 'disabled' : '' }} required />
                            </div>

                            <div class="form-group">
                                <label>Email</label><br>
                                <input value="{{ old('email', isset($user) ? $user->email : '') }}" name="email"
                                       type="email" class="form-control" {{ isset($user) ? 'disabled' : '' }}
                                       required />
                            </div>

                            @if (!isset($user))
                            <div class="form-group">
                                <label>Password</label><br>
                                <input name="password" type="password" class="form-control peakable" required />
                            </div>

                            <div class="form-group">
                                <label>Confirm Password</label><br>
                                <input name="password_confirmation" type="password" class="form-control peakable"
                                       required />
                            </div>
                            @endif

                            <div class="form-group">
                                <label>Roles</label><br>
                                @foreach ($roles as $role)
                                <label class="user-select-none">
                                    <input value="{{ $role->name }}" type="radio" name="role" {{ isset($user) &&
                                           $user->hasRole($role) ? 'checked' : '' }} />
                                    {{ $role->name }}
                                </label>
                                <br>
                                @endforeach
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">{{ isset($user) ? 'Submit Changes' : 'Add'
                                    }}</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_js')
<script type="module">
    import { makePeakable } from '/js/peakable.js'
    makePeakable('.peakable')
</script>
<script>
    @if (isset($user))
    const handleToggleStatus = (e) => {
        e.preventDefault();
        const del = confirm('{{ $user->status ? "Disable" : "Re-Activate" }}' + " this user?");
        if(del) {
            const form = document.querySelector('#toggleStatusForm');
            form.submit();
        }
    }
    @endif
</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">Users</h4>

                    @can('create_users')
                    <a class="btn btn-success text-white" href="{{ route('admin.users.create') }}">+ Add user</a>
                    @endcan
                </div>

                <div class="card-body">
                    <table class="table m-0 border">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Status</th>
                                <th>Role</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            @if (!$user->hasRole('Super-Admin'))
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->status ? 'Active' : 'Disabled' }}</td>
                                <td>
                                    @foreach ($user->roles as $role)
                                    {{ $role->name }}
                                    {{ !$loop->last ? ' / ' : '' }}
                                    @endforeach
                                </td>
                                <td>
                                    @can('edit_users')
                                    <a class="btn btn-primary"
                                       href="{{ route('admin.users.edit', $user->id) }}">Edit</a>
                                    @endcan
                                </td>
                            </tr>
                            @endif
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_css')
@endsection
@section('additional_js')
@endsection