routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SignController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Session()->reflash();
    return redirect('/search');
});
Route::get('/home', function () {
    Session()->reflash();
    return redirect('/search');
});

Auth::routes(['register' => false]);

Route::resource('signs', 'SignController');

Route::get('/search', function () {
    return view('search');
})->name('search');

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {

        // admin sign routes
        Route::get('/signs', [SignController::class, 'index'])->middleware('permission:create_signs|edit_signs|delete_signs')->name('signs.index');
        Route::get('/signs/create', [SignController::class, 'create'])->middleware('permission:create_signs')->name('signs.create');
        Route::post('/signs', [SignController::class, 'store'])->middleware('permission:create_signs')->name('signs.store');
        Route::get('/signs/{sign}/edit', [SignController::class, 'edit'])->middleware('permission:edit_signs')->name('signs.edit');
        Route::put('/signs/{sign}', [SignController::class, 'update'])->middleware('permission:edit_signs')->name('signs.update');
        Route::delete('/signs/{sign}', [SignController::class, 'destroy'])->middleware('permission:delete_signs')->name('signs.destroy');

        // admin user routes
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:create_users|edit_users|delete_users')->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->middleware('permission:create_users')->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:create_users')->name('users.store');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->middleware('permission:edit_users')->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:edit_users')->name('users.update');
        Route::delete('/users/{id}/toggleStatus', [UserController::class, 'toggleStatus'])->middleware('permission:delete_users')->name('users.toggleStatus');

        // admin role routes
        Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:create_roles|edit_roles|delete_roles')->name('roles.index');
        Route::get('/roles/create', [RoleController::class, 'create'])->middleware('permission:create_roles')->name('roles.create');
        Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:create_roles')->name('roles.store');
        Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->middleware('permission:edit_roles')->name('roles.edit');
        Route::put('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:edit_roles')->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:delete_roles')->name('roles.destroy');
    });

Route::get('/changePassword', [UserController::class, 'changePasswordForm'])->name('changePasswordForm');
Route::post('/changePassword', [UserController::class, 'changePassword'])->name('changePassword');

Route::get('/{page}', 'PageController')
    ->name('page')
    ->where('page', 'about|services|contact');

app/Sign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

class Sign extends Model {
    use \Spatie\Tags\HasTags;

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted() {
        static::deleted(function ($sign) {
            if (Storage::exists($sign->video)) {
                Storage::delete($sign->video);
                flashMessage('Related file deleted', 'success');
            }
        });
    }
}

app/Http/Controllers/Admin/SignController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Sign;
use Spatie\Tags\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

class SignController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $signs = Sign::get();
        return view('admin.signs.index', compact('signs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $categories = Tag::getWithType('category')->toArray();
        $categoriesData = array_map(function ($cat) {
            return (object) array('id' => $cat['name']['en'], 'text' => $cat['name']['en']);
        }, $categories);

        $meanings = Tag::getWithType('meaning')->toArray();
        $meaningsData = array_map(function ($cat) {
            return (object) array('id' => $cat['name']['en'], 'text' => $cat['name']['en']);
        }, $meanings);
        return view('admin.signs.create', compact('categoriesData', 'meaningsData'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // Validate Request Data

        // Store Videos to Storage
        $video = '';
        // $explanation_video = '';
        if ($request->has('video')) {
            $video = $request->video->store('public/signs');
        }
        // if ($request->has('explanation_video')) {
        //     $explanation_video = $request->explanation_video->store('public/signs');
        // }

        // Save Sign
        $sign = new Sign();
        $sign->video = $video;
        $sign->explanation = $request->explanation;
        // $sign->explanation_video = $explanation_video;
        $sign->save();

        // Attach Meaning Tags to Sign
        $sign->syncTagsWithType($request->meaning, 'meaning');

        // Attach Category Tags to Sign
        $sign->syncTagsWithType($request->category, 'category');


        flashMessage('Sign created', 'success');

        return redirect()->route('admin.signs.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function edit(Sign $sign) {
        $categories = Tag::getWithType('category')->toArray();
        $categoriesData = array_map(function ($cat) use ($sign) {
            return (object) array(
                'id' => $cat['name']['en'],
                'text' => $cat['name']['en'],
                'selected' => Sign::withAllTags([$cat['name']['en']], 'category')->get()->contains($sign)
            );
        }, $categories);

        $meanings = Tag::getWithType('meaning')->toArray();
        $meaningsData = array_map(function ($cat) use ($sign) {
            return (object) array(
                'id' => $cat['name']['en'],
                'text' => $cat['name']['en'],
                'selected' => Sign::withAllTags([$cat['name']['en']], 'meaning')->get()->contains($sign)
            );
        }, $meanings);
        return view('admin.signs.create', compact('categoriesData', 'meaningsData', 'sign'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sign $sign) {
        // Store Videos to Storage
        if ($request->has('video')) {

            $video = $request->video->store('public/signs');
            $oldVideo = $sign->video;
            $sign->video = $video;

            if ($oldVideo != '') {
                Storage::delete($oldVideo);
                flashMessage('Old file deleted', 'success');
            }
        }

        // Save Sign
        $sign->explanation = $request->explanation;
        $sign->save();

        // Attach Meaning Tags to Sign
        $sign->syncTagsWithType($request->meaning, 'meaning');

        // Attach Category Tags to Sign
        $sign->syncTagsWithType($request->category, 'category');

        flashMessage('Sign updated', 'success');

        return redirect()->route('admin.signs.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sign $sign) {
        $sign->delete();

        flashMessage('Sign deleted', 'success');

        return redirect()->route('admin.signs.index');
    }
}

app/Http/Controllers/SignController.php
<?php

namespace App\Http\Controllers;

use App\Sign;
use Illuminate\Http\Request;
use Spatie\Tags\Tag;

class SignController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $meanings = Tag::withType('meaning')->orderBy('name')->where('name', 'LIKE', '%' . $request->q . '%')->get()->sortBy('name', SORT_NATURAL | SORT_FLAG_CASE);
        $query = Sign::withAnyTags($meanings, 'meaning');

        if ($request->q) {
            $title = "Search results for: '" . $request->q . "'";
        } else if ($request->cat) {
            $title = "Category: " . $request->cat;
            $query->withAllTags([$request->cat], 'category');
        } else {
            $title = "Browse Signs";
        }
        $signs = $query->get();

        return view('signs.index', compact('signs', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('signs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // Validate Request Data

        // Store Videos to Storage
        $video = '';
        $explanation_video = '';
        if ($request->has('video')) {
            $video = $request->video->store('public/signs');
        }
        if ($request->has('explanation_video')) {
            $explanation_video = $request->explanation_video->store('public/signs');
        }

        // Save Sign
        $sign = new Sign();
        $sign->video = $video;
        $sign->explanation = $request->explanation;
        $sign->explanation_video = $explanation_video;
        $sign->save();

        // Attach Meaning Tags to Sign
        $sign->syncTagsWithType($request->meaning, 'meaning');

        // Attach Category Tags to Sign
        $sign->syncTagsWithType($request->category, 'category');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function show(Sign $sign) {
        $related = Sign::withAnyTags($sign->tags)->where('id', '!=', $sign->id)->get();
        return view('signs.show', compact('sign', 'related'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function edit(Sign $sign) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sign $sign) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sign  $sign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sign $sign) {
        //
    }
}

resources/views/admin/signs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">{{ isset($sign) ? 'Edit Sign' : 'Add Sign' }}</h4>
                    @if (isset($sign))

                    <a class="btn btn-danger text-white" href="#" onclick="handleDelete(event)">Delete
                        Sign</a>
                    <form id="deleteForm" action="{{ route('admin.signs.destroy', $sign->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                    </form>
                    @endif
                </div>

                <div class="card-body">

                    <form action="{{ isset($sign) ? route('admin.signs.update', $sign->id) : route('admin.signs.store') }}"
                          method="POST" enctype="multipart/form-data">
                        @csrf

                        {{-- Change method if update --}}
                        @if (isset($sign))
                        @method('PUT')
                        @endif

                        <div class="card-block">

                            <div class="form-group">
                                <label>Video</label>
                                @if (isset($sign) && $sign->video != '')
                                <video width=100% controls>
                                    <source src="{{ \Storage::url($sign->video) }}" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                                Replace Video: <input type="file" name="video" class="replace-video">
                                {{-- <div class="replace_video-wrapper">
                                    <button class="replace_video-button">
                                        <a href="javascript: void(0)">Replace Video</a>
                                    </button>
                                    <input type="file" name="video" class="replace_video-input" />
                                </div> --}}
                                @else
                                <input type="file" class="form-control" placeholder="Upload Video" name="video">
                                @endif
                            </div>

                            <div class="form-group">
                                <label>Meaning</label><br>
                                <select class="select2-meaning form-control" name="meaning[]" multiple>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Category</label><br>
                                <select class="select2-category form-control" name="category[]" multiple>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Explanation</label>
                                <textarea class="form-control" name="explanation">{{ isset($sign) ? $sign->explanation :
                                    '' }}</textarea>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">{{ isset($sign) ? 'Submit Changes' : 'Add'
                                    }}</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_css')
<link rel="stylesheet" href="/css/select2.min.css">
@endsection
@section('additional_js')
<script src="/js/select2.min.js"></script>
<script>
    // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('.select2-meaning').select2({
        tags: true,
        data: @json($meaningsData),
        // minimumInputLength: 1
    });

    $('.select2-category').select2({
        tags: true,
        data: @json($categoriesData),
        // minimumInputLength: 1
    });
});

const handleDelete = (e) => {
    e.preventDefault();
    const del = confirm('DELETE this sign?');
    if(del) {
        const form = document.querySelector('#deleteForm');
        form.submit();
    }
}
</script>
@endsection

resources/views/admin/signs/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="m-0">Signs</h4>

                    @can('create_signs')
                    <a class="btn btn-success text-white" href="{{ route('admin.signs.create') }}">+ Add Sign</a>
                    @endcan
                </div>

                <div class="card-body">
                    <table class="table m-0 border">
                        <thead>
                            <tr>
                                <th>Meanings</th>
                                <th>Video</th>
                                <th>Categories</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($signs as $sign)
                            <tr>
                                <td>
                                    <a target="_blank" href="{{ route('signs.show', $sign->id) }}">
                                        @foreach ($sign->tagsWithType('meaning') as $meaning)
                                        {{ $meaning->name }} {{ (!$loop->last ? ' / ' : '') }}
                                        @endforeach
                                    </a>
                                </td>
                                <td>
                                    {{ $sign->video ? 'Yes' : 'No' }}
                                </td>
                                <td>
                                    @foreach ($sign->tagsWithType('category') as $category)
                                    <a target="_blank" href="{{ route('signs.index', ['cat' => $category->name]) }}">{{
                                        $category->name }}</a>
                                    {{(!$loop->last ? ', ' : '') }}
                                    @endforeach
                                </td>
                                <td>
                                    @can('edit_signs')
                                    <a href="{{ route('admin.signs.edit', $sign->id) }}">Edit</a>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional_css')
@endsection
@section('additional_js')
@endsection